name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  PATH_STAGE_1: "./Infrastructure/digitalocean/infrastructure-live/test-v1/stage1/"
  PATH_STAGE_2: "./Infrastructure/digitalocean/infrastructure-live/test-v1/stage2/"

jobs:
  provision_infra:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provision infra
        env:
          DO_API_TOKEN: ${{secrets.DO_API_TOKEN }}
          DO_BUCKET_ACCESS_KEY: ${{ secrets.DO_BUCKET_ACCESS_KEY }}
          DO_BUCKET_SECRET_KEY: ${{ secrets.DO_BUCKET_SECRET_KEY }}
        run: |
          terraform --version
          terraform -chdir=$PATH_STAGE_1 init -var="digital_ocean_api_token=${{ secrets.DO_API_TOKEN }}" -backend-config="access_key=${{ secrets.DO_BUCKET_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.DO_BUCKET_SECRET_KEY }}"
          terraform -chdir=$PATH_STAGE_1 plan -var="digital_ocean_api_token=${{ secrets.DO_API_TOKEN }}"
          terraform -chdir=$PATH_STAGE_1 apply -var="digital_ocean_api_token=${{ secrets.DO_API_TOKEN }}" --auto-approve
